### ISSUE TITLE
服务器目前不在线

### ISSUE THREAD

**Issue by kldhsh123** [GamerNoTitle/CraftMon#2]
我开启了query并将query端口设置为mc服务器端口,但是在服务器开启的情况下还是显示服务器目前不在线

**Comment by kldhsh123** [comment]
控制台有一段报错：Uncaught Error: Syntax error, unrecognized expression: #
    at se.error (jquery.min.js:2:13639)
    at se.tokenize (jquery.min.js:2:21650)
    at se.compile (jquery.min.js:2:21753)
    at se.select (jquery.min.js:2:22998)
    at se (jquery.min.js:2:7116)
    at se.matches (jquery.min.js:2:12962)
    at S.filter (jquery.min.js:2:24772)
    at j (jquery.min.js:2:24623)
    at S.fn.init.filter (jquery.min.js:2:25133)
    at HTMLAnchorElement.<anonymous> (main.js:40:17)
se.error @ jquery.min.js:2
se.tokenize @ jquery.min.js:2
se.compile @ jquery.min.js:2
se.select @ jquery.min.js:2
se @ jquery.min.js:2
se.matches @ jquery.min.js:2
S.filter @ jquery.min.js:2
j @ jquery.min.js:2
filter @ jquery.min.js:2
(anonymous) @ main.js:40
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

**Comment by GamerNoTitle** [comment]
服务器是否开放的对应端口的UDP协议呢？
CraftMon的后台有没有报错？

**Comment by kldhsh123** [comment]
开放了协议,后台没有报错,只有浏览器控制台报错

**Comment by GamerNoTitle** [comment]
给个预览地址？

**Comment by kldhsh123** [comment]
http://c.nxw.so/demo

**Comment by GamerNoTitle** [comment]
yysy，感觉不是前端渲染的问题，jq就算报错也不应该影响渲染，渲染是后端的事
服务器版本？用的是什么端（Spigot还是什么其他的）？（估计月底才有时间上电脑看，学业有点忙

**Comment by kldhsh123** [comment]
1.20.1forge

**Comment by GamerNoTitle** [comment]
我月底回去看看吧 目前我的猜想是你的这个网站跟你的服务器没连上

**Comment by GamerNoTitle** [comment]
应该是你服务器问题，我这边测的正常
检查一下服务器UDP是否打开了，有没有被防火墙BLOCK掉

**Comment by thun888** [comment]
`<a href="#" class="icon solid fa fa-home">`修改为`<a href="#home" class="icon solid fa fa-home">`即可，不过这个问题也不影响服务器状态显示啊awa
